ALTER TABLE "SchoolNfcPolicy"
ADD COLUMN IF NOT EXISTS "gateOfflineEnabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "canteenOfflineEnabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN IF NOT EXISTS "gateSnapshotValidHours" INTEGER NOT NULL DEFAULT 24,
ADD COLUMN IF NOT EXISTS "canteenSnapshotValidHours" INTEGER NOT NULL DEFAULT 12,
ADD COLUMN IF NOT EXISTS "maxOfflineSpendPerStudentPerDay" INTEGER NOT NULL DEFAULT 5000,
ADD COLUMN IF NOT EXISTS "maxOfflineSpendPerTransaction" INTEGER NOT NULL DEFAULT 2000,
ADD COLUMN IF NOT EXISTS "maxOfflineSpendPerDeviceSession" INTEGER NOT NULL DEFAULT 100000,
ADD COLUMN IF NOT EXISTS "unknownCardOfflinePolicy" TEXT NOT NULL DEFAULT 'DENY',
ADD COLUMN IF NOT EXISTS "frozenCardOfflinePolicy" TEXT NOT NULL DEFAULT 'DENY',
ADD COLUMN IF NOT EXISTS "deactivatedCardOfflinePolicy" TEXT NOT NULL DEFAULT 'DENY',
ADD COLUMN IF NOT EXISTS "offlineConflictPolicy" TEXT NOT NULL DEFAULT 'ALLOW_AND_FLAG';

ALTER TABLE "NfcOfflineDevice"
ADD COLUMN IF NOT EXISTS "location" TEXT,
ADD COLUMN IF NOT EXISTS "deviceTokenHash" TEXT,
ADD COLUMN IF NOT EXISTS "mode" TEXT NOT NULL DEFAULT 'GATE',
ADD COLUMN IF NOT EXISTS "status" TEXT NOT NULL DEFAULT 'ACTIVE',
ADD COLUMN IF NOT EXISTS "lastSeenAt" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "lastSnapshotAt" TIMESTAMP(3);
