import { z } from "zod";
import { assetUrlSchema } from "../utils/assetUrls";

function blankStringToUndefined(value: unknown) {
  if (typeof value !== "string") return value;
  return value.trim() === "" ? undefined : value;
}

const optionalTrimmedString = (defaultValue = "") =>
  z.preprocess(blankStringToUndefined, z.string().trim().optional().default(defaultValue));

const optionalEmailString = (message: string) =>
  z.preprocess(
    blankStringToUndefined,
    z.string().trim().email(message).optional().default(""),
  );

const optionalUrlString = (message: string) =>
  z.preprocess(
    blankStringToUndefined,
    z.string().trim().url(message).optional().default(""),
  );

const optionalPhoneString = z.preprocess(
  blankStringToUndefined,
  z
    .string()
    .trim()
    .regex(/^[+]?[0-9\s()-]+$/, "Enter a valid phone number or leave blank.")
    .optional()
    .default(""),
);

export const SETTING_SECTIONS = [
  "school",
  "academic",
  "reports",
  "reportPersonalization",
  "marksheets",
  "ocr",
  "grading",
  "approval",
  "appearance",
] as const;

export type SettingSection = (typeof SETTING_SECTIONS)[number];

export const assessmentTypeSchema = z.enum(["BOT", "MOT", "EOT", "TERM_SUMMARY"]);

export const schoolProfileSchema = z.object({
  schoolName: z.string().trim().min(1, "School name is required."),
  schoolCode: z.string().trim().min(1, "School code is required."),
  address: optionalTrimmedString(),
  phone: optionalPhoneString,
  email: optionalEmailString("Enter a valid email address or leave blank."),
  website: optionalUrlString("Enter a valid URL or leave blank."),
  headTeacherName: z.string().trim().default("Head Teacher"),
  reportFooterText: z.string().trim().default("This report was generated by School Connect Reports First."),
  marksheetFooterText: z.string().trim().default("Blank means missing, not zero."),
  logoUrl: assetUrlSchema,
  schoolSections: z.array(z.enum(["NURSERY", "PRIMARY", "SECONDARY", "COMBINED"])).min(1).default(["SECONDARY"]),
});

export const academicSetupSchema = z.object({
  activeAcademicYear: z.string().trim().min(1, "Active academic year is required."),
  activeTerm: z.string().trim().min(1, "Active term is required."),
  defaultAssessmentType: assessmentTypeSchema.default("EOT"),
  supportedAssessmentTypes: z.array(assessmentTypeSchema).min(1, "Select at least one assessment type."),
  termStartDate: z.string().trim().regex(/^\d{4}-\d{2}-\d{2}$/, "Use YYYY-MM-DD."),
  termEndDate: z.string().trim().regex(/^\d{4}-\d{2}-\d{2}$/, "Use YYYY-MM-DD."),
}).superRefine((value, ctx) => {
  if (value.termStartDate > value.termEndDate) {
    ctx.addIssue({ code: "custom", path: ["termEndDate"], message: "Term end date must be after the start date." });
  }
  if (!value.supportedAssessmentTypes.includes(value.defaultAssessmentType)) {
    ctx.addIssue({ code: "custom", path: ["defaultAssessmentType"], message: "Default assessment must be supported." });
  }
});

export const reportSettingsSchema = z.object({
  showOverallPosition: z.boolean().default(false),
  showClassAverage: z.boolean().default(true),
  showGradeKey: z.boolean().default(true),
  showSchoolLogo: z.boolean().default(true),
  printDensity: z.enum(["compact", "standard"]).default("standard"),
  signatureMode: z.enum(["name_only", "name_and_signature_line"]).default("name_and_signature_line"),
  defaultHmCommentTemplate: z.string().trim().default(""),
  defaultClassTeacherCommentTemplate: z.string().trim().default(""),
});

export const reportPersonalizationBrandingSchema = z.object({
  schoolNameOverride: z.string().trim().default(""),
  motto: z.string().trim().default(""),
  address: z.string().trim().default(""),
  phone: optionalPhoneString,
  email: optionalEmailString("Enter a valid email address or leave blank."),
  website: optionalUrlString("Enter a valid URL or leave blank."),
  primaryColor: z.string().trim().default("#0f2a5e"),
  secondaryColor: z.string().trim().default("#c9a227"),
  logoUrl: assetUrlSchema,
  stampUrl: assetUrlSchema,
  headteacherSignatureUrl: assetUrlSchema,
  headteacherName: z.string().trim().default("Head Teacher"),
  footerMessage: z.string().trim().default(""),
});

export const reportPersonalizationLayoutSchema = z.object({
  templateStyle: z.enum(["classic", "modern", "compact", "detailed"]).default("classic"),
  showStudentPhoto: z.boolean().default(false),
  showPosition: z.boolean().default(false),
  showStreamPosition: z.boolean().default(false),
  showClassAverage: z.boolean().default(true),
  showGradingScale: z.boolean().default(true),
  showSubjectTeacherInitials: z.boolean().default(false),
  showAttendance: z.boolean().default(false),
  showParentCommentBox: z.boolean().default(true),
  showFeesBalance: z.boolean().default(false),
  reportTitleOverride: z.string().trim().default(""),
});

export const reportPersonalizationGradeBandSchema = z.object({
  sortOrder: z.number().int().min(0).default(0),
  name: z.string().trim().min(1, "Band name is required."),
  minScore: z.number().int().min(0).max(100),
  maxScore: z.number().int().min(0).max(100),
  grade: z.string().trim().min(1, "Grade label is required."),
  points: z.number().optional(),
  remark: z.string().trim().default(""),
}).superRefine((band, ctx) => {
  if (band.minScore > band.maxScore) {
    ctx.addIssue({ code: "custom", path: ["minScore"], message: "Minimum score cannot be greater than maximum score." });
  }
});

export const reportPersonalizationCommentSchema = z.object({
  sortOrder: z.number().int().min(0).default(0),
  type: z.enum(["classTeacher", "headteacher", "subject", "conduct", "attendance"]),
  performanceBand: z.enum(["excellent", "good", "average", "weak", "poor"]).optional(),
  comment: z.string().trim().min(1, "Comment text is required."),
  active: z.boolean().default(true),
});

export const reportPersonalizationSchema = z.object({
  branding: reportPersonalizationBrandingSchema,
  layout: reportPersonalizationLayoutSchema,
  gradingScheme: z.array(reportPersonalizationGradeBandSchema).min(1, "Add at least one grade band."),
  commentBank: z.array(reportPersonalizationCommentSchema).default([]),
}).superRefine((value, ctx) => {
  const sorted = value.gradingScheme.slice().sort((a, b) => a.sortOrder - b.sortOrder);
  const coverage = new Array(101).fill(0) as number[];
  sorted.forEach((band, index) => {
    for (let score = band.minScore; score <= band.maxScore; score += 1) {
      coverage[score] += 1;
      if (coverage[score] > 1) {
        ctx.addIssue({ code: "custom", path: ["gradingScheme", index], message: `Grade band overlaps at score ${score}.` });
        break;
      }
    }
  });
  for (let score = 0; score <= 100; score += 1) {
    if (coverage[score] === 0) {
      ctx.addIssue({ code: "custom", path: ["gradingScheme"], message: `Grading scheme has a gap at score ${score}.` });
      break;
    }
  }
});

export const marksheetSettingsSchema = z.object({
  printStyle: z.enum(["rich_black", "standard"]).default("rich_black"),
  includeQrCode: z.boolean().default(true),
  includeHumanReadableMarksheetId: z.boolean().default(true),
  validMarkValues: z.literal("0-100, AB, EX").default("0-100, AB, EX"),
  blankMeans: z.literal("missing").default("missing"),
  onePageTarget: z.boolean().default(true),
  repeatTableHeaderOnContinuationPages: z.literal(true).default(true),
  signaturesOnlyOnFinalPage: z.boolean().default(true),
});

export const ocrSettingsSchema = z.object({
  minimumConfidenceForSuggestion: z.number().min(0).max(1).default(0.7),
  useSplitMarkAsPrimarySource: z.literal(true).default(true),
  useWrittenMarkAsConfirmation: z.literal(true).default(true),
  ocrRemarks: z.literal(false).default(false),
  acceptOcrSuggestionsAutomatically: z.literal(false).default(false),
  requireOperatorReviewBeforeCommit: z.literal(true).default(true),
});

export const gradeSchema = z.object({
  label: z.enum(["D1", "D2", "C3", "C4", "C5", "C6", "P7", "P8", "F9"]),
  minScore: z.number().int().min(0).max(100),
  maxScore: z.number().int().min(0).max(100),
  descriptor: z.string().trim().optional().default(""),
}).superRefine((grade, ctx) => {
  if (grade.minScore > grade.maxScore) {
    ctx.addIssue({ code: "custom", path: ["minScore"], message: "Minimum score cannot be greater than maximum score." });
  }
});

export const gradingScaleSchema = z.object({
  grades: z.array(gradeSchema).length(9, "All nine grades must be configured."),
}).superRefine((value, ctx) => {
  const labels = value.grades.map((grade) => grade.label);
  for (const expected of ["D1", "D2", "C3", "C4", "C5", "C6", "P7", "P8", "F9"]) {
    if (!labels.includes(expected as (typeof labels)[number])) {
      ctx.addIssue({ code: "custom", path: ["grades"], message: `Missing grade ${expected}.` });
    }
  }

  const coverage = new Array(101).fill(0) as number[];
  value.grades.forEach((grade, index) => {
    for (let score = grade.minScore; score <= grade.maxScore; score += 1) {
      coverage[score] += 1;
      if (coverage[score] > 1) {
        ctx.addIssue({ code: "custom", path: ["grades", index], message: `Grade ${grade.label} overlaps at score ${score}.` });
        break;
      }
    }
  });
  const missing = coverage.findIndex((count) => count === 0);
  if (missing >= 0) {
    ctx.addIssue({ code: "custom", path: ["grades"], message: `Grading scale has a gap at score ${missing}.` });
  }
});

export const approvalSettingsSchema = z.object({
  requireDryRunBeforeCommit: z.boolean().default(true),
  protectCommittedMarksFromEditing: z.boolean().default(true),
  requireHmFinalizationBeforeReportPrintRelease: z.boolean().default(false),
  allowHmToEditComments: z.boolean().default(true),
  allowHmToEditRawMarks: z.literal(false).default(false),
  reopenFinalizedReportsRequiresReason: z.boolean().default(true),
  keepAuditTrail: z.boolean().default(true),
});

export const appearanceSettingsSchema = z.object({
  appDensity: z.enum(["compact", "comfortable"]).default("comfortable"),
  sidebarWidth: z.enum(["compact", "standard", "wide"]).default("standard"),
  printStyle: z.enum(["rich_black", "standard"]).default("rich_black"),
  fontSize: z.enum(["small", "standard", "large"]).default("standard"),
});

export const settingsSectionsSchema = z.object({
  school: schoolProfileSchema,
  academic: academicSetupSchema,
  reports: reportSettingsSchema,
  reportPersonalization: reportPersonalizationSchema,
  marksheets: marksheetSettingsSchema,
  ocr: ocrSettingsSchema,
  grading: gradingScaleSchema,
  approval: approvalSettingsSchema,
  appearance: appearanceSettingsSchema,
});

export type SchoolProfileSettings = z.infer<typeof schoolProfileSchema>;
export type AcademicSetupSettings = z.infer<typeof academicSetupSchema>;
export type ReportSettings = z.infer<typeof reportSettingsSchema>;
export type ReportPersonalizationSettings = z.infer<typeof reportPersonalizationSchema>;
export type ReportPersonalizationBrandingSettings = z.infer<typeof reportPersonalizationBrandingSchema>;
export type ReportPersonalizationLayoutSettings = z.infer<typeof reportPersonalizationLayoutSchema>;
export type ReportPersonalizationGradeBand = z.infer<typeof reportPersonalizationGradeBandSchema>;
export type ReportPersonalizationComment = z.infer<typeof reportPersonalizationCommentSchema>;
export type MarksheetSettings = z.infer<typeof marksheetSettingsSchema>;
export type OcrSettings = z.infer<typeof ocrSettingsSchema>;
export type GradingScaleSettings = z.infer<typeof gradingScaleSchema>;
export type ApprovalSettings = z.infer<typeof approvalSettingsSchema>;
export type AppearanceSettings = z.infer<typeof appearanceSettingsSchema>;
export type SettingsSections = z.infer<typeof settingsSectionsSchema>;

export type SettingsResponse = {
  schoolCode: string;
  sections: SettingsSections;
  updatedAt: string | null;
  updatedBy: string | null;
};

export const defaultSettingsSections: SettingsSections = {
  school: {
    schoolName: "Uganda High School",
    schoolCode: "SCU-PREVIEW",
    address: "",
    phone: "",
    email: "",
    website: "",
    headTeacherName: "Head Teacher",
    reportFooterText: "This report was generated by School Connect Reports First.",
    marksheetFooterText: "Valid entries: 0-100, AB, EX. Blank means missing, not zero.",
    logoUrl: "",
    schoolSections: ["SECONDARY"],
  },
  academic: {
    activeAcademicYear: "2025/2026",
    activeTerm: "Term 1",
    defaultAssessmentType: "EOT",
    supportedAssessmentTypes: ["BOT", "MOT", "EOT", "TERM_SUMMARY"],
    termStartDate: "2025-09-01",
    termEndDate: "2025-12-12",
  },
  reports: {
    showOverallPosition: false,
    showClassAverage: true,
    showGradeKey: true,
    showSchoolLogo: true,
    printDensity: "standard",
    signatureMode: "name_and_signature_line",
    defaultHmCommentTemplate: "",
    defaultClassTeacherCommentTemplate: "",
  },
  reportPersonalization: {
    branding: {
      schoolNameOverride: "",
      motto: "",
      address: "",
      phone: "",
      email: "",
      website: "",
      primaryColor: "#0f2a5e",
      secondaryColor: "#c9a227",
      logoUrl: "",
      stampUrl: "",
      headteacherSignatureUrl: "",
      headteacherName: "Head Teacher",
      footerMessage: "",
    },
    layout: {
      templateStyle: "classic",
      showStudentPhoto: false,
      showPosition: false,
      showStreamPosition: false,
      showClassAverage: true,
      showGradingScale: true,
      showSubjectTeacherInitials: false,
      showAttendance: false,
      showParentCommentBox: true,
      showFeesBalance: false,
      reportTitleOverride: "",
    },
    gradingScheme: [
      { sortOrder: 0, name: "Distinction", minScore: 80, maxScore: 100, grade: "D1", points: 1, remark: "Excellent" },
      { sortOrder: 1, name: "Very good", minScore: 75, maxScore: 79, grade: "D2", points: 2, remark: "Very good" },
      { sortOrder: 2, name: "Good", minScore: 70, maxScore: 74, grade: "C3", points: 3, remark: "Good" },
      { sortOrder: 3, name: "Credit", minScore: 65, maxScore: 69, grade: "C4", points: 4, remark: "Credit" },
      { sortOrder: 4, name: "Credit", minScore: 60, maxScore: 64, grade: "C5", points: 5, remark: "Credit" },
      { sortOrder: 5, name: "Pass", minScore: 50, maxScore: 59, grade: "C6", points: 6, remark: "Pass" },
      { sortOrder: 6, name: "Basic pass", minScore: 45, maxScore: 49, grade: "P7", points: 7, remark: "Basic pass" },
      { sortOrder: 7, name: "Needs support", minScore: 40, maxScore: 44, grade: "P8", points: 8, remark: "Needs support" },
      { sortOrder: 8, name: "Below standard", minScore: 0, maxScore: 39, grade: "F9", points: 9, remark: "Below standard" },
    ],
    commentBank: [],
  },
  marksheets: {
    printStyle: "rich_black",
    includeQrCode: true,
    includeHumanReadableMarksheetId: true,
    validMarkValues: "0-100, AB, EX",
    blankMeans: "missing",
    onePageTarget: true,
    repeatTableHeaderOnContinuationPages: true,
    signaturesOnlyOnFinalPage: true,
  },
  ocr: {
    minimumConfidenceForSuggestion: 0.7,
    useSplitMarkAsPrimarySource: true,
    useWrittenMarkAsConfirmation: true,
    ocrRemarks: false,
    acceptOcrSuggestionsAutomatically: false,
    requireOperatorReviewBeforeCommit: true,
  },
  grading: {
    grades: [
      { label: "D1", minScore: 80, maxScore: 100, descriptor: "Excellent" },
      { label: "D2", minScore: 75, maxScore: 79, descriptor: "Very good" },
      { label: "C3", minScore: 70, maxScore: 74, descriptor: "Good" },
      { label: "C4", minScore: 65, maxScore: 69, descriptor: "Credit" },
      { label: "C5", minScore: 60, maxScore: 64, descriptor: "Credit" },
      { label: "C6", minScore: 50, maxScore: 59, descriptor: "Pass" },
      { label: "P7", minScore: 45, maxScore: 49, descriptor: "Basic pass" },
      { label: "P8", minScore: 40, maxScore: 44, descriptor: "Needs support" },
      { label: "F9", minScore: 0, maxScore: 39, descriptor: "Below standard" },
    ],
  },
  approval: {
    requireDryRunBeforeCommit: true,
    protectCommittedMarksFromEditing: true,
    requireHmFinalizationBeforeReportPrintRelease: false,
    allowHmToEditComments: true,
    allowHmToEditRawMarks: false,
    reopenFinalizedReportsRequiresReason: true,
    keepAuditTrail: true,
  },
  appearance: {
    appDensity: "comfortable",
    sidebarWidth: "standard",
    printStyle: "rich_black",
    fontSize: "standard",
  },
};

export const sectionSchemas = {
  school: schoolProfileSchema,
  academic: academicSetupSchema,
  reports: reportSettingsSchema,
  reportPersonalization: reportPersonalizationSchema,
  marksheets: marksheetSettingsSchema,
  ocr: ocrSettingsSchema,
  grading: gradingScaleSchema,
  approval: approvalSettingsSchema,
  appearance: appearanceSettingsSchema,
} as const;

